package commands

import (
	"fmt"
	"os"
	"os/exec"
	"strings"

	"github.com/caseydavenport/cube-tools/pkg/flag"
	"github.com/sirupsen/logrus"
	"github.com/spf13/cobra"
)

// Define a cobra command for parsing a single deck file.
var ParseDirectoryCmd = &cobra.Command{
	Use:   "parse-dir",
	Short: "Parse a directory of deck files",
	Run: func(cmd *cobra.Command, args []string) {
		// Verify input.
		if date == "" {
			logrus.Fatal("Must specify a date for the deck.")
		}
		if draftID == "" {
			logrus.Fatal("Must specify a draft ID for the deck.")
		}

		parseDeckDir(deckInputDir, fileType, date, draftID)
	},
}

func init() {
	// Add flags for the command to parse a directory of deck files.
	flags := ParseDirectoryCmd.Flags()
	flag.StringVarP(flags, &date, "date", "t", "DATE", "", "Date, in YYYY-MM-DD format")
	flag.StringVarP(flags, &deckInputDir, "deck-dir", "d", "DIR", "", "Directory containing deck files to parse.")
	flag.StringVarP(flags, &fileType, "filetype", "f", "TYPE", ".csv", "File type to look for in the deck-dir.")
	flag.StringVarP(flags, &prefix, "prefix", "p", "PREFIX", "", "Prefix to match in the deck file names. Stripped before parsing.")
	flag.StringVarP(flags, &draftID, "draft", "", "DRAFT", "", "Draft ID - used as the output directory")
}

// work represents a piece of parsing work to be done.
type work struct {
	player string
	path   string
}

func nameFromDeckFilename(filename string) string {
	nicknames := map[string]string{
		"jumms":      "james",
		"maserstorm": "dom",
		"phinsup":    "cara",

		"pawl noerros": "paul",
		"pawl nawwwis": "paul",

		"grrg": "greg",

		"jenjen": "jen",
		"jenno":  "jen",

		"pyrolol": "mattd",
	}
	trimmed := strings.ToLower(strings.TrimPrefix(strings.Split(filename, ".")[0], prefix))
	if name, ok := nicknames[trimmed]; ok {
		return name
	}
	return trimmed
}

func parseDeckDir(deckDir, fileType, date, draftID string) {
	logc := logrus.WithFields(logrus.Fields{
		"directory": deckDir,
		"filetype":  fileType,
	})

	// Make sure the output directory exists.
	outdir := fmt.Sprintf("data/polyverse/%s", date)
	err := os.MkdirAll(outdir, os.ModePerm)
	if err != nil {
		panic(err)
	}

	// Gather files to load.
	files := []work{}

	// Load files from CSV dir.
	fileNames, err := os.ReadDir(deckDir)
	if err != nil {
		panic(err)
	}
	for _, f := range fileNames {
		// Skip some well-known files that we never want to process.
		if strings.Contains(f.Name(), "cubecobra.txt") {
			// These are generated by this tool and should just be skipped.
			continue
		}
		if prefix != "" && !strings.HasPrefix(f.Name(), prefix) {
			// Skip files that don't match the prefix, if specified.
			continue
		}
		if strings.HasSuffix(f.Name(), fileType) {
			// Add the file, using the file name as the player name (minus the filetype)
			files = append(files, work{
				player: nameFromDeckFilename(f.Name()),
				path:   fmt.Sprintf("%s/%s", deckDir, f.Name()),
			})
		}
	}

	if len(files) == 0 {
		logc.Info("No files to process.")
		return
	}
	logc.WithField("num", len(files)).Info("Processing deck files.")

	// Determine if we need to auto-name the file.
	for _, f := range files {
		parseSingleDeck(f.path, f.player, labels, date, draftID)
	}

	snaptshotFilename := fmt.Sprintf("%s/cube-snapshot.json", outdir)
	if _, err := os.Stat(snaptshotFilename); err != nil {
		// Write the cube-snapshot file to the draft directory if it doesn't exist already.
		//
		// This ensures we have a snapshot of the cube as it was on this date
		// for historical tracking and comparisons.
		// TODO: This is a bit of a hack, and assumes this command is being run
		// within the root of this project. That's OK for now since I am the only user.
		cmd := exec.Command("cp", "data/polyverse/cube.json", snaptshotFilename)
		if err := cmd.Run(); err != nil {
			panic(err)
		}
	}
}
